2021-06-07 18:39:50.176  [WARNING] 18852 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /api/login1
2021-06-07 18:57:04.538  [WARNING] 8768 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /api/login/
2021-06-09 00:25:49,682  [WARNING] 1680 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-09 00:26:04,092  [WARNING] 12752 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-09 00:26:12,817  [WARNING] 12752 --- [Thread-3] [django.request:230][log:log_response]: Method Not Allowed: /api/login
2021-06-10 15:39:23,737  [WARNING] 6432 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-10 15:52:03,381  [ERROR] 19280 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\utils\deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\middleware\common.py", line 94, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/courses/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2021-06-10 19:14:10,606  [WARNING] 16172 --- [Thread-1] [django.request:230][log:log_response]: Forbidden: /courses
2021-06-10 19:17:09,893  [WARNING] 9448 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-10 19:20:29,539  [WARNING] 4076 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /courses
2021-06-10 19:26:43,287  [WARNING] 13680 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /courses
2021-06-10 21:20:37,783  [WARNING] 13680 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /course/java.jpeg
2021-06-11 14:50:08,648  [WARNING] 8332 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-11 14:52:34,674  [WARNING] 7112 --- [Thread-3] [django.request:230][log:log_response]: Forbidden: /courses
2021-06-11 21:25:43,875  [WARNING] 5016 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /courses
2021-06-11 21:27:46,220  [WARNING] 912 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /courses
2021-06-11 21:28:01,705  [WARNING] 1324 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /courses
2021-06-11 21:30:25,515  [WARNING] 14776 --- [Thread-3] [django.request:230][log:log_response]: Forbidden: /courses
2021-06-11 22:29:15,087  [ERROR] 3432 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 74, in wrap_attributeerrors
    yield
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
AttributeError: 'Authenticated' object has no attribute 'authenticate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "C:\Users\TJ\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 78, in wrap_attributeerrors
    raise exc.with_traceback(info[2])
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 74, in wrap_attributeerrors
    yield
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
rest_framework.request.WrappedAttributeError: 'Authenticated' object has no attribute 'authenticate'
2021-06-11 22:31:15,176  [ERROR] 13884 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 74, in wrap_attributeerrors
    yield
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
AttributeError: 'Authenticated' object has no attribute 'authenticate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "C:\Users\TJ\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 78, in wrap_attributeerrors
    raise exc.with_traceback(info[2])
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 74, in wrap_attributeerrors
    yield
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
rest_framework.request.WrappedAttributeError: 'Authenticated' object has no attribute 'authenticate'
2021-06-11 22:31:24,091  [ERROR] 13884 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 74, in wrap_attributeerrors
    yield
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
AttributeError: 'Authenticated' object has no attribute 'authenticate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "C:\Users\TJ\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 78, in wrap_attributeerrors
    raise exc.with_traceback(info[2])
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 74, in wrap_attributeerrors
    yield
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
rest_framework.request.WrappedAttributeError: 'Authenticated' object has no attribute 'authenticate'
2021-06-11 22:35:19,908  [ERROR] 9192 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 74, in wrap_attributeerrors
    yield
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
AttributeError: 'Authenticated' object has no attribute 'authenticate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "C:\Users\TJ\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 78, in wrap_attributeerrors
    raise exc.with_traceback(info[2])
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 74, in wrap_attributeerrors
    yield
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
rest_framework.request.WrappedAttributeError: 'Authenticated' object has no attribute 'authenticate'
2021-06-11 22:35:47,429  [ERROR] 9192 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 74, in wrap_attributeerrors
    yield
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
AttributeError: 'Authenticated' object has no attribute 'authenticate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "C:\Users\TJ\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 78, in wrap_attributeerrors
    raise exc.with_traceback(info[2])
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 74, in wrap_attributeerrors
    yield
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
rest_framework.request.WrappedAttributeError: 'Authenticated' object has no attribute 'authenticate'
2021-06-11 22:53:43,765  [WARNING] 2440 --- [Thread-1] [django.request:230][log:log_response]: Forbidden: /courses
2021-06-11 22:54:52,168  [WARNING] 2440 --- [Thread-1] [django.request:230][log:log_response]: Forbidden: /courses
2021-06-11 23:01:14,619  [WARNING] 13896 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /course
2021-06-11 23:01:21,098  [WARNING] 13896 --- [Thread-3] [django.request:230][log:log_response]: Forbidden: /courses
2021-06-11 23:03:11,604  [ERROR] 7052 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 278, in get_permissions
    return [permission() for permission in self.permission_classes]
TypeError: 'type' object is not iterable
2021-06-12 15:39:41,571  [WARNING] 12648 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-12 15:41:16,603  [WARNING] 8896 --- [Thread-3] [django.request:230][log:log_response]: Forbidden: /courses
2021-06-12 15:41:50,044  [WARNING] 8896 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /courses
2021-06-12 16:00:15,653  [WARNING] 684 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /media/images/java.jpeg
2021-06-12 16:29:47,825  [WARNING] 10916 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-12 16:45:53,051  [WARNING] 7556 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-12 16:45:57,416  [WARNING] 7556 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-12 16:46:00,963  [WARNING] 7556 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-12 16:46:43,442  [WARNING] 3536 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-12 16:49:21,861  [WARNING] 12180 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-12 17:02:16,708  [WARNING] 8568 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:03:25,726  [WARNING] 13656 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:03:33,851  [WARNING] 12712 --- [Thread-2] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:04:59,128  [WARNING] 13072 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:06:11,152  [WARNING] 10544 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:06:29,342  [WARNING] 10544 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:06:30,901  [WARNING] 10544 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:08:15,943  [WARNING] 13912 --- [Thread-5] [django.request:230][log:log_response]: Not Found: /register/
2021-06-12 17:10:45,903  [WARNING] 3156 --- [Thread-7] [django.request:230][log:log_response]: Not Found: /user/login
2021-06-12 17:12:09,119  [WARNING] 3156 --- [Thread-7] [django.request:230][log:log_response]: Not Found: /user/login
2021-06-12 17:12:13,027  [WARNING] 3156 --- [Thread-7] [django.request:230][log:log_response]: Not Found: /user/login
2021-06-12 17:19:44,153  [WARNING] 17272 --- [Thread-8] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:19:48,917  [WARNING] 17272 --- [Thread-8] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:25:25,447  [WARNING] 8476 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:25:50,882  [WARNING] 8476 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:26:10,276  [WARNING] 2024 --- [Thread-2] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:27:51,509  [WARNING] 15284 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:30:01,626  [WARNING] 14372 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:31:56,115  [WARNING] 14372 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:33:27,989  [WARNING] 1116 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:33:33,330  [WARNING] 1116 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:33:43,588  [WARNING] 1116 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:33:50,830  [WARNING] 1116 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:33:58,194  [WARNING] 1116 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:35:07,036  [WARNING] 11936 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /register
2021-06-12 17:36:07,722  [WARNING] 260 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /user/login
2021-06-12 17:36:13,703  [WARNING] 260 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /user/login
2021-06-12 17:44:49,387  [WARNING] 13052 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /user/login
2021-06-12 17:44:57,024  [WARNING] 13052 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /user/login
2021-06-12 17:53:08,243  [WARNING] 17336 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /user/login/
2021-06-12 17:58:32,662  [WARNING] 17336 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /user/login
2021-06-12 18:01:00,302  [ERROR] 17336 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /uploadFiles
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\resource\views.py", line 67, in dispatch
    return super(FileUploadView, self).dispatch(request,*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\login\login_token.py", line 91, in resolve_token1
    return func(self,request,args)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\resource\views.py", line 48, in post
    course = Course.objects.filter(cno=course_id).first()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 287, in first
    result = queryset[0]
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 191, in __getitem__
    queryset._cursor[key],
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1666, in _cursor
    self._cursor_obj = self._collection.find(self._query, **self._cursor_args)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1715, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 90, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 185, in accept
    return visitor.visit_query(self)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 79, in visit_query
    return transform.query(self.document, **query.query)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\transform.py", line 120, in query
    value = field.prepare_query_value(op, value)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\fields.py", line 2174, in prepare_query_value
    return self.value_decorator(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-06-12 18:11:04,210  [INFO] 15448 --- [Thread-4] [apps.views:87][views:get]: 下载Python课程报告统一规范.pdf
2021-06-12 18:17:36,098  [WARNING] 16448 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /user/login/
2021-06-12 18:22:33,347  [INFO] 9096 --- [Thread-3] [login.views:25][views:post]: login success
2021-06-12 18:22:33,480  [INFO] 9096 --- [Thread-3] [login.views:36][views:post]: 学生SA20225429登录成功！
2021-06-12 18:22:33,481  [INFO] 9096 --- [Thread-3] [login.views:37][views:post]: login success
2021-06-12 18:27:03,526  [WARNING] 16988 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /user/register
2021-06-12 18:27:09,940  [WARNING] 16988 --- [Thread-3] [django.request:230][log:log_response]: Unauthorized: /user/register
2021-06-12 18:30:11,724  [INFO] 4536 --- [Thread-3] [login.views:81][views:post]: studentSA20225435注册成功！
2021-06-12 18:30:25,501  [INFO] 4536 --- [Thread-3] [login.views:35][views:post]: 学生SA20225435登录成功！
2021-06-12 18:30:25,502  [INFO] 4536 --- [Thread-3] [login.views:36][views:post]: login success
2021-06-12 20:45:26,623  [INFO] 12460 --- [Thread-1] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:02:25,967  [INFO] 16636 --- [Thread-1] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:14:12,857  [INFO] 13936 --- [Thread-2] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:14:25,476  [INFO] 13936 --- [Thread-2] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:14:28,007  [INFO] 13936 --- [Thread-2] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:14:29,401  [INFO] 13936 --- [Thread-2] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:14:33,386  [INFO] 13936 --- [Thread-2] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:15:06,095  [INFO] 13936 --- [Thread-2] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:15:09,185  [INFO] 13936 --- [Thread-2] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:15:58,964  [INFO] 13936 --- [Thread-2] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:16:32,314  [INFO] 5316 --- [Thread-3] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:18:17,823  [INFO] 8052 --- [Thread-4] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:18:18,628  [INFO] 8052 --- [Thread-4] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:18:19,460  [INFO] 8052 --- [Thread-4] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:18:21,730  [INFO] 8052 --- [Thread-4] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:18:22,396  [INFO] 8052 --- [Thread-4] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:20:27,000  [INFO] 8052 --- [Thread-4] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:22:08,667  [INFO] 8052 --- [Thread-4] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:24:46,828  [INFO] 9652 --- [Thread-1] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:32:01,950  [WARNING] 7528 --- [Thread-1] [django.request:230][log:log_response]: Forbidden: /courses/1
2021-06-12 21:32:19,708  [INFO] 7528 --- [Thread-1] [login.views:35][views:post]: 学生SA20225435登录成功！
2021-06-12 21:32:19,709  [INFO] 7528 --- [Thread-1] [login.views:36][views:post]: login success
2021-06-12 21:33:16,291  [ERROR] 7528 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses/1
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 69, in update
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:34:26,060  [ERROR] 7528 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses/1
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 69, in update
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:34:31,919  [ERROR] 7528 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses/1
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 69, in update
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:39:48,975  [ERROR] 15580 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses/1
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 70, in update
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:40:03,673  [ERROR] 15580 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses/1
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 70, in update
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:41:28,488  [ERROR] 13764 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses/1
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 70, in update
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:41:29,981  [ERROR] 13764 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses/1
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 70, in update
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:41:47,760  [ERROR] 2768 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses/1
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 70, in update
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:43:41,645  [ERROR] 6844 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses/1
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 62, in retrieve
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:44:01,726  [ERROR] 10244 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses/1
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 62, in retrieve
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:46:15,403  [ERROR] 14472 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses/1
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 62, in retrieve
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:46:40,770  [ERROR] 14472 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses/2
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 62, in retrieve
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:48:15,329  [ERROR] 15912 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses/2
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 62, in retrieve
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 21:48:25,414  [INFO] 17072 --- [Thread-1] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:48:25,685  [WARNING] 17072 --- [Thread-1] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-12 21:50:33,136  [INFO] 7944 --- [Thread-1] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:50:33,229  [WARNING] 7944 --- [Thread-1] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-12 21:51:51,532  [INFO] 8116 --- [Thread-1] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:51:53,071  [ERROR] 8116 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /user/info
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\login\login_token.py", line 92, in resolve_token1
    return func(self,request,args)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\user\views.py", line 20, in get
    teacher = Teacher.objects.filter(uid=args.get('uid')).first()
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 287, in first
    result = queryset[0]
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 191, in __getitem__
    queryset._cursor[key],
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1666, in _cursor
    self._cursor_obj = self._collection.find(self._query, **self._cursor_args)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1715, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 90, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 185, in accept
    return visitor.visit_query(self)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 79, in visit_query
    return transform.query(self.document, **query.query)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\transform.py", line 120, in query
    value = field.prepare_query_value(op, value)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\fields.py", line 2174, in prepare_query_value
    return self.value_decorator(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-06-12 21:52:52,423  [INFO] 8116 --- [Thread-1] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 21:52:52,538  [ERROR] 8116 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /user/info
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\login\login_token.py", line 92, in resolve_token1
    return func(self,request,args)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\user\views.py", line 20, in get
    teacher = Teacher.objects.filter(uid=args.get('uid')).first()
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 287, in first
    result = queryset[0]
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 191, in __getitem__
    queryset._cursor[key],
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1666, in _cursor
    self._cursor_obj = self._collection.find(self._query, **self._cursor_args)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1715, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 90, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 185, in accept
    return visitor.visit_query(self)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 79, in visit_query
    return transform.query(self.document, **query.query)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\queryset\transform.py", line 120, in query
    value = field.prepare_query_value(op, value)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\mongoengine\fields.py", line 2174, in prepare_query_value
    return self.value_decorator(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-06-12 21:55:35,037  [INFO] 7728 --- [Thread-3] [login.views:35][views:post]: 学生SA20225435登录成功！
2021-06-12 21:55:35,038  [INFO] 7728 --- [Thread-3] [login.views:36][views:post]: login success
2021-06-12 21:56:16,376  [WARNING] 7728 --- [Thread-3] [django.request:230][log:log_response]: Method Not Allowed: /user/info
2021-06-12 21:56:21,582  [ERROR] 7728 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /user/info
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\login\login_token.py", line 92, in resolve_token1
    return func(self,request,args)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\user\views.py", line 20, in get
    teacher = Teacher.objects.filter(uid=args.get('uid')).first()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 287, in first
    result = queryset[0]
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 191, in __getitem__
    queryset._cursor[key],
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1666, in _cursor
    self._cursor_obj = self._collection.find(self._query, **self._cursor_args)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1715, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 90, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 185, in accept
    return visitor.visit_query(self)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 79, in visit_query
    return transform.query(self.document, **query.query)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\transform.py", line 120, in query
    value = field.prepare_query_value(op, value)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\fields.py", line 2174, in prepare_query_value
    return self.value_decorator(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-06-12 21:56:29,845  [WARNING] 7728 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /user/info/
2021-06-12 21:56:58,598  [ERROR] 7728 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /user/info
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\login\login_token.py", line 92, in resolve_token1
    return func(self,request,args)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\user\views.py", line 20, in get
    teacher = Teacher.objects.filter(uid=args.get('uid')).first()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 287, in first
    result = queryset[0]
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 191, in __getitem__
    queryset._cursor[key],
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1666, in _cursor
    self._cursor_obj = self._collection.find(self._query, **self._cursor_args)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1715, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 90, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 185, in accept
    return visitor.visit_query(self)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 79, in visit_query
    return transform.query(self.document, **query.query)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\transform.py", line 120, in query
    value = field.prepare_query_value(op, value)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\fields.py", line 2174, in prepare_query_value
    return self.value_decorator(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-06-12 22:01:28,868  [ERROR] 1036 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /user/info
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\login\login_token.py", line 92, in resolve_token1
    return func(self,request,args)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\user\views.py", line 21, in get
    teacher = Teacher.objects.filter(uid=args.get('uid')).first()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 287, in first
    result = queryset[0]
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 191, in __getitem__
    queryset._cursor[key],
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1666, in _cursor
    self._cursor_obj = self._collection.find(self._query, **self._cursor_args)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1715, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 90, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 185, in accept
    return visitor.visit_query(self)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 79, in visit_query
    return transform.query(self.document, **query.query)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\transform.py", line 120, in query
    value = field.prepare_query_value(op, value)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\fields.py", line 2174, in prepare_query_value
    return self.value_decorator(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-06-12 22:02:17,848  [ERROR] 8636 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /user/info
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\login\login_token.py", line 92, in resolve_token1
    return func(self,request,args)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\user\views.py", line 21, in get
    teacher = Teacher.objects.filter(uid=args.get('uid')).first()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 287, in first
    result = queryset[0]
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 191, in __getitem__
    queryset._cursor[key],
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1666, in _cursor
    self._cursor_obj = self._collection.find(self._query, **self._cursor_args)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\base.py", line 1715, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 90, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 185, in accept
    return visitor.visit_query(self)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\visitor.py", line 79, in visit_query
    return transform.query(self.document, **query.query)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\queryset\transform.py", line 120, in query
    value = field.prepare_query_value(op, value)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\mongoengine\fields.py", line 2174, in prepare_query_value
    return self.value_decorator(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-06-12 22:02:55,367  [INFO] 8636 --- [Thread-3] [login.views:35][views:post]: 学生SA20225435登录成功！
2021-06-12 22:02:55,367  [INFO] 8636 --- [Thread-3] [login.views:36][views:post]: login success
2021-06-12 22:03:36,913  [INFO] 10728 --- [Thread-1] [login.views:35][views:post]: 学生SA20225435登录成功！
2021-06-12 22:03:36,913  [INFO] 10728 --- [Thread-1] [login.views:36][views:post]: login success
2021-06-12 22:03:45,526  [WARNING] 10728 --- [Thread-1] [django.request:230][log:log_response]: Method Not Allowed: /user/info
2021-06-12 22:05:03,368  [INFO] 9620 --- [Thread-1] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 22:05:03,914  [WARNING] 9620 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /course/showCourse
2021-06-12 22:05:11,399  [WARNING] 9620 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /course/1/10
2021-06-12 22:05:15,049  [WARNING] 9620 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /course/showCourse
2021-06-12 22:06:51,108  [WARNING] 9620 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /student/getStudent
2021-06-12 22:07:08,291  [WARNING] 9620 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /course/showCourse
2021-06-12 22:07:15,989  [WARNING] 9620 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /course/showCourse
2021-06-12 22:07:47,086  [ERROR] 6252 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses/2
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 62, in retrieve
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 22:09:14,398  [ERROR] 14404 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses/2
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 62, in retrieve
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 22:12:12,441  [ERROR] 6696 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses/2
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 63, in retrieve
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 22:12:21,648  [ERROR] 6696 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /courses/2
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 63, in retrieve
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 22:12:51,047  [ERROR] 9996 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses/2
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 63, in retrieve
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 22:20:05,901  [WARNING] 16056 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /course/recommend
2021-06-12 22:20:38,531  [WARNING] 16828 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /courses
2021-06-12 22:21:00,113  [WARNING] 5420 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-12 22:30:57,835  [WARNING] 13008 --- [Thread-6] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 22:30:57,837  [WARNING] 16304 --- [Thread-5] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 22:30:57,839  [WARNING] 9404 --- [Thread-7] [django.request:230][log:log_response]: Not Found: /teacher/getCourseInfo/1
2021-06-12 22:32:40,183  [WARNING] 15420 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /courses
2021-06-12 22:32:57,568  [WARNING] 15420 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /courses
2021-06-12 22:32:58,832  [WARNING] 15420 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /courses
2021-06-12 22:33:01,528  [WARNING] 15420 --- [Thread-3] [django.request:230][log:log_response]: Forbidden: /course
2021-06-12 22:33:19,090  [WARNING] 15420 --- [Thread-3] [django.request:230][log:log_response]: Forbidden: /course
2021-06-12 22:33:33,571  [WARNING] 15420 --- [Thread-3] [django.request:230][log:log_response]: Method Not Allowed: /user/login
2021-06-12 22:33:38,924  [INFO] 15420 --- [Thread-3] [login.views:35][views:post]: 学生SA20225429登录成功！
2021-06-12 22:33:38,925  [INFO] 15420 --- [Thread-3] [login.views:36][views:post]: login success
2021-06-12 22:37:43,917  [WARNING] 12524 --- [Thread-8] [django.request:230][log:log_response]: Not Found: /user/logout
2021-06-12 22:38:25,428  [INFO] 12848 --- [Thread-9] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 22:39:03,661  [WARNING] 14064 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /course/1
2021-06-12 22:40:17,083  [WARNING] 9952 --- [Thread-10] [django.request:230][log:log_response]: Not Found: /media/images/course/default.jpeg
2021-06-12 22:40:22,548  [WARNING] 9952 --- [Thread-10] [django.request:230][log:log_response]: Not Found: /media/images/course/default.jpeg
2021-06-12 22:40:23,158  [WARNING] 9952 --- [Thread-10] [django.request:230][log:log_response]: Not Found: /media/images/course/default.jpeg
2021-06-12 22:40:30,605  [WARNING] 9952 --- [Thread-10] [django.request:230][log:log_response]: Not Found: /media/images/course/default.jpeg
2021-06-12 22:41:05,938  [WARNING] 9952 --- [Thread-10] [django.request:230][log:log_response]: Not Found: /media/images/course/default.png
2021-06-12 22:41:39,957  [WARNING] 12848 --- [Thread-9] [django.request:230][log:log_response]: Not Found: /teacher/getCourseInfo/1
2021-06-12 22:41:39,980  [WARNING] 7404 --- [Thread-12] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 22:41:39,981  [WARNING] 15476 --- [Thread-13] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 22:42:08,762  [WARNING] 9952 --- [Thread-10] [django.request:230][log:log_response]: Not Found: /media/images/course/default.png
2021-06-12 22:42:36,541  [WARNING] 9952 --- [Thread-10] [django.request:230][log:log_response]: Not Found: /media/images/course/default.png
2021-06-12 22:44:26,346  [INFO] 7404 --- [Thread-12] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 22:44:35,492  [INFO] 7404 --- [Thread-12] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 22:44:49,014  [WARNING] 7404 --- [Thread-12] [django.request:230][log:log_response]: Not Found: /user/logout
2021-06-12 22:44:56,444  [WARNING] 7404 --- [Thread-12] [django.request:230][log:log_response]: Not Found: /student/getStudent
2021-06-12 22:45:16,523  [INFO] 15680 --- [Thread-15] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-12 22:45:24,327  [WARNING] 15680 --- [Thread-15] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-12 22:45:27,699  [WARNING] 15680 --- [Thread-15] [django.request:230][log:log_response]: Not Found: /course/1/10
2021-06-12 22:49:41,124  [WARNING] 15680 --- [Thread-15] [django.request:230][log:log_response]: Not Found: /teacher/getCourseInfo/1
2021-06-12 22:49:41,131  [WARNING] 7396 --- [Thread-17] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 22:49:41,144  [WARNING] 17328 --- [Thread-18] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 22:50:21,764  [WARNING] 4128 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /course/1
2021-06-12 22:50:44,926  [WARNING] 3356 --- [Thread-19] [django.request:230][log:log_response]: Not Found: /course/1
2021-06-12 22:50:46,214  [WARNING] 3356 --- [Thread-19] [django.request:230][log:log_response]: Not Found: /course/1
2021-06-12 22:50:53,869  [WARNING] 9324 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 22:50:53,871  [WARNING] 13848 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /teacher/getCourseInfo/1
2021-06-12 22:50:53,874  [WARNING] 11712 --- [Thread-4] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 22:50:54,632  [WARNING] 14164 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /course/1
2021-06-12 22:50:58,195  [WARNING] 11712 --- [Thread-4] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-12 22:51:02,292  [WARNING] 13848 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 22:51:02,294  [WARNING] 9324 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 22:51:02,295  [WARNING] 11712 --- [Thread-4] [django.request:230][log:log_response]: Not Found: /teacher/getCourseInfo/1
2021-06-12 22:51:35,235  [WARNING] 11712 --- [Thread-4] [django.request:230][log:log_response]: Not Found: /course/1/10
2021-06-12 22:51:37,196  [ERROR] 12456 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /courses/2
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 62, in retrieve
    instance = self.get_object()
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
AttributeError: 'Authenticated' object has no attribute 'has_object_permission'
2021-06-12 22:51:38,150  [WARNING] 10332 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-12 22:51:38,152  [WARNING] 17140 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-12 22:52:02,456  [WARNING] 12528 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 22:52:02,457  [WARNING] 8548 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /teacher/getCourseInfo/1
2021-06-12 22:52:02,459  [WARNING] 260 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 22:52:57,705  [WARNING] 7872 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /courses/id=2
2021-06-12 22:53:12,250  [WARNING] 7872 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /courses/
2021-06-12 22:53:53,844  [WARNING] 9244 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /courses/2
2021-06-12 22:53:55,957  [WARNING] 9244 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /courses/2
2021-06-12 22:56:12,641  [WARNING] 12588 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 22:56:12,643  [WARNING] 7796 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 22:56:45,009  [WARNING] 12588 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 22:56:45,011  [WARNING] 7796 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 22:58:14,963  [WARNING] 16076 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-12 23:01:09,112  [WARNING] 2492 --- [Thread-6] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 23:01:09,117  [WARNING] 16032 --- [Thread-7] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 23:01:17,267  [WARNING] 2492 --- [Thread-6] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 23:01:17,268  [WARNING] 16032 --- [Thread-7] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 23:04:34,774  [WARNING] 2492 --- [Thread-6] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 23:04:34,775  [WARNING] 16032 --- [Thread-7] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 23:04:35,717  [WARNING] 2492 --- [Thread-6] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 23:04:35,719  [WARNING] 16032 --- [Thread-7] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 23:05:06,852  [WARNING] 11108 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 23:05:06,853  [WARNING] 16884 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 23:07:09,448  [WARNING] 16376 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 23:07:09,450  [WARNING] 15416 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 23:07:57,011  [WARNING] 15416 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 23:07:57,017  [WARNING] 16376 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /course/getSource/1
2021-06-12 23:16:14,075  [WARNING] 10492 --- [Thread-5] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-12 23:16:32,587  [WARNING] 10492 --- [Thread-5] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-13 16:08:04,074  [WARNING] 2136 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /favicon.ico
2021-06-13 16:09:13,972  [INFO] 7292 --- [Thread-2] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-13 16:15:48,003  [WARNING] 4884 --- [Thread-1] [django.request:230][log:log_response]: Forbidden: /course/
2021-06-13 16:16:13,149  [WARNING] 4884 --- [Thread-1] [django.request:230][log:log_response]: Method Not Allowed: /user/login
2021-06-13 16:16:17,774  [INFO] 4884 --- [Thread-1] [login.views:35][views:post]: 学生SA20225429登录成功！
2021-06-13 16:16:17,774  [INFO] 4884 --- [Thread-1] [login.views:36][views:post]: login success
2021-06-13 16:20:25,750  [WARNING] 4296 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /user/logout
2021-06-13 16:21:02,522  [INFO] 1664 --- [Thread-4] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-13 16:21:06,524  [INFO] 11616 --- [Thread-5] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-13 16:21:28,363  [INFO] 7492 --- [Thread-1] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-13 16:21:51,019  [WARNING] 5376 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-13 16:34:50,894  [WARNING] 13156 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 16:34:50,895  [WARNING] 4396 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 16:34:52,177  [ERROR] 12236 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\paginator.py", line 46, in validate_number
    number = int(number)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 58, in get
    current_page = paginator.page(page)  # 获取当前页的数据
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\paginator.py", line 73, in page
    number = self.validate_number(number)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\paginator.py", line 48, in validate_number
    raise PageNotAnInteger(_('That page number is not an integer'))
django.core.paginator.PageNotAnInteger: That page number is not an integer
2021-06-13 16:34:54,709  [WARNING] 4396 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-13 16:35:20,278  [ERROR] 12236 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 58, in get
    current_page = paginator.page(page)  # 获取当前页的数据
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\paginator.py", line 73, in page
    number = self.validate_number(number)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\paginator.py", line 55, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: That page contains no results
2021-06-13 16:35:21,182  [WARNING] 4396 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-13 16:35:37,278  [ERROR] 12236 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 58, in get
    current_page = paginator.page(page)  # 获取当前页的数据
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\paginator.py", line 73, in page
    number = self.validate_number(number)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\paginator.py", line 55, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: That page contains no results
2021-06-13 16:36:12,278  [ERROR] 12236 --- [Thread-3] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 58, in get
    current_page = paginator.page(page)  # 获取当前页的数据
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\paginator.py", line 73, in page
    number = self.validate_number(number)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\paginator.py", line 55, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: That page contains no results
2021-06-13 16:38:38,962  [ERROR] 1468 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 58, in get
    current_page = paginator.page(page)  # 获取当前页的数据
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\paginator.py", line 73, in page
    number = self.validate_number(number)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\paginator.py", line 55, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: That page contains no results
2021-06-13 16:39:13,928  [WARNING] 9820 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-13 16:40:24,374  [WARNING] 148 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-13 16:41:05,254  [WARNING] 148 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-13 16:41:10,914  [WARNING] 148 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 16:41:10,915  [WARNING] 1744 --- [Thread-4] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 16:41:39,934  [ERROR] 8240 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 58, in get
    if pag_count < page:
TypeError: '<' not supported between instances of 'int' and 'str'
2021-06-13 16:41:56,583  [ERROR] 8240 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 58, in get
    if pag_count < page:
TypeError: '<' not supported between instances of 'int' and 'str'
2021-06-13 16:42:05,792  [ERROR] 8240 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 58, in get
    if pag_count < page:
TypeError: '<' not supported between instances of 'int' and 'str'
2021-06-13 16:42:24,159  [ERROR] 8240 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 58, in get
    if pag_count < page:
TypeError: '<' not supported between instances of 'int' and 'str'
2021-06-13 16:44:11,520  [WARNING] 13092 --- [Thread-1] [django.request:230][log:log_response]: Bad Request: /course/
2021-06-13 16:50:17,239  [ERROR] 256 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 63, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:50:24,196  [ERROR] 256 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 63, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:50:25,391  [ERROR] 12392 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 63, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:51:17,199  [WARNING] 256 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-13 16:51:20,347  [ERROR] 256 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 63, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:51:21,196  [WARNING] 256 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 16:51:21,229  [WARNING] 7528 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 16:51:22,693  [ERROR] 7528 --- [Thread-2] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 63, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:51:33,458  [ERROR] 8588 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 64, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:51:36,519  [ERROR] 8588 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\工程实践\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 64, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:51:42,354  [WARNING] 14240 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 16:51:42,355  [WARNING] 4284 --- [Thread-1] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 16:51:43,013  [ERROR] 14240 --- [Thread-2] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 64, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:51:48,484  [ERROR] 14240 --- [Thread-2] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 64, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:51:51,048  [ERROR] 14240 --- [Thread-2] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 64, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:51:52,111  [ERROR] 14240 --- [Thread-2] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 64, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:51:54,174  [ERROR] 14240 --- [Thread-2] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 64, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:52:34,331  [ERROR] 14240 --- [Thread-2] [django.request:230][log:log_response]: Internal Server Error: /course/
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\course\views.py", line 64, in get
    data['total'] = len(courses)
TypeError: list indices must be integers or slices, not str
2021-06-13 16:55:26,648  [WARNING] 304 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-13 16:55:28,697  [WARNING] 304 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 16:55:28,703  [WARNING] 12332 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 16:58:52,777  [WARNING] 304 --- [Thread-2] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-13 17:24:59,285  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:24:59,390  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:24:59,465  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:24:59,533  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:24:59,608  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:24:59,678  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:24:59,749  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:24:59,822  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:24:59,906  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:00,020  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:00,098  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:00,178  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:00,271  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:00,374  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:00,457  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:00,541  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:00,653  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:00,745  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:00,820  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:00,901  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:00,973  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:01,049  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:01,125  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:01,238  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:01,313  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:01,397  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:01,474  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:01,569  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:01,655  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:01,788  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:01,863  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:01,963  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:02,068  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:02,186  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:02,316  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:02,425  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:02,509  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:02,637  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:02,762  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:02,885  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:03,014  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:03,171  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:03,291  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:03,517  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:03,671  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:03,764  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:03,861  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:04,067  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:04,166  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:04,292  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:04,583  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:04,697  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:04,982  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:05,196  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:05,488  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:05,562  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:05,671  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:05,762  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:05,866  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:05,975  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:06,085  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:06,218  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:06,476  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:06,670  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:06,796  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:07,066  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:07,181  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:07,370  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:07,477  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:07,662  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:07,774  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:07,872  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:08,076  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:08,171  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:08,367  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:08,461  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:08,595  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:08,794  [WARNING] 7720 --- [Thread-5] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:10,040  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:10,175  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:10,363  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:10,562  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:10,652  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:10,856  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:10,957  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:11,068  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:11,250  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:11,357  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:11,450  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:11,557  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:11,754  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:11,969  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:12,086  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:12,283  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:12,367  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:12,580  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:12,762  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:12,869  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:13,057  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:13,159  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:13,265  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:13,374  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:13,461  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:13,664  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:13,794  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:13,992  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:14,275  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:14,511  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:14,689  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:14,866  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:15,062  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:15,173  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:15,376  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:15,566  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:15,784  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:15,874  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:16,088  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:16,274  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:16,467  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:16,659  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:16,804  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:17,070  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:17,171  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:17,275  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:17,491  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:17,766  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:17,860  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:17,967  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:18,078  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:18,258  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:18,371  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:18,563  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:18,661  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:18,780  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:18,886  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:19,078  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:19,320  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:19,491  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:19,671  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:19,769  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:19,989  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:20,363  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:20,515  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:20,657  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:20,900  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:21,068  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:21,160  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:21,443  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:21,685  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:21,882  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:22,196  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:22,472  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:22,676  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:22,890  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:23,063  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:23,311  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:23,583  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:23,669  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:23,870  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:23,975  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:24,068  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:24,173  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:24,275  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:24,482  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:24,566  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:24,759  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:25,004  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:25,274  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:25,480  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:25,574  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:25,690  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:25,980  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:26,078  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:26,404  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:26,666  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:26,789  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:26,960  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:27,053  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:27,163  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:27,293  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:27,480  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:27,669  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:27,764  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:27,859  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:28,060  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:28,162  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:28,285  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:28,463  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:28,557  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:28,675  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:28,762  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:28,859  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:28,971  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:29,061  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:29,152  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:29,250  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:29,334  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:29,458  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:29,568  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:29,656  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:29,756  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:29,851  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:29,957  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:30,051  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:30,134  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:30,218  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:30,308  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:30,409  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:30,501  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:30,598  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:30,700  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:30,780  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:30,863  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:30,959  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:31,071  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:31,177  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:31,267  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:31,391  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:31,506  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:31,633  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:31,713  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:31,809  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:31,917  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:32,019  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:32,113  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:32,216  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:32,332  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:32,442  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:32,539  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:32,636  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:32,730  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:32,832  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:32,916  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:33,008  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:33,101  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:33,191  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:33,280  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:33,383  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:33,477  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:33,574  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:33,682  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:33,805  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:33,902  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:34,012  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:34,102  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:34,198  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:34,276  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:34,350  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:34,475  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:34,570  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:34,688  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:34,770  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:34,870  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:34,955  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:35,082  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:35,164  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:35,327  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:35,435  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:35,554  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:35,665  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:35,824  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:35,925  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:36,041  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:36,252  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:36,433  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:36,754  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:37,055  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:37,235  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:37,324  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:37,564  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:37,739  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:37,924  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:38,041  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:38,217  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:38,326  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:38,418  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:38,526  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:38,890  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:39,021  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:39,134  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:39,328  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:39,556  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:39,737  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:39,817  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:39,937  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:40,047  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:40,228  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:40,446  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:40,618  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:40,818  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:40,913  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:41,027  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:41,244  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:41,426  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:41,531  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:41,718  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:41,909  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:42,015  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:42,123  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:42,336  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:42,463  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:42,640  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:42,915  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:43,043  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:43,268  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:43,438  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:43,653  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:43,830  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:44,011  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:44,220  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:44,419  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:44,656  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:44,918  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:45,018  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:45,139  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:45,217  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:45,470  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:45,635  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:45,715  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:45,821  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:46,036  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:46,140  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:46,237  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:46,452  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:46,624  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:46,759  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:46,931  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:47,040  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:47,219  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:47,317  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:47,510  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:47,645  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:47,817  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:47,913  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:48,123  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:48,332  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:48,464  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:48,736  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:48,820  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:49,012  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:49,116  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:49,216  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:49,436  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:49,517  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:49,627  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:49,721  [WARNING] 12972 --- [Thread-6] [django.request:230][log:log_response]: Forbidden: /user/info
2021-06-13 17:25:58,882  [INFO] 11572 --- [Thread-7] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-13 17:26:46,773  [WARNING] 6680 --- [Thread-1] [django.request:230][log:log_response]: Forbidden: /course/recommend
2021-06-13 17:28:36,332  [WARNING] 11572 --- [Thread-7] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 17:28:36,335  [WARNING] 6380 --- [Thread-8] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 17:29:26,714  [WARNING] 11572 --- [Thread-7] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 17:29:26,715  [WARNING] 6380 --- [Thread-8] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 17:30:28,086  [WARNING] 248 --- [Thread-9] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 17:30:28,123  [WARNING] 6940 --- [Thread-10] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 17:34:19,885  [WARNING] 7660 --- [Thread-11] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 17:34:19,887  [WARNING] 11904 --- [Thread-12] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 17:35:12,695  [WARNING] 9752 --- [Thread-13] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 17:35:12,709  [WARNING] 2596 --- [Thread-14] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 17:36:35,941  [WARNING] 3224 --- [Thread-15] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 17:36:35,943  [WARNING] 1392 --- [Thread-16] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 17:39:09,348  [WARNING] 12252 --- [Thread-17] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 17:39:09,352  [WARNING] 3936 --- [Thread-18] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 17:40:28,336  [WARNING] 3936 --- [Thread-18] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 17:40:28,339  [WARNING] 12252 --- [Thread-17] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 17:40:42,241  [WARNING] 3936 --- [Thread-18] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 17:40:42,246  [WARNING] 12252 --- [Thread-17] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 17:43:30,892  [WARNING] 12252 --- [Thread-17] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 17:43:30,894  [WARNING] 3936 --- [Thread-18] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 17:44:03,602  [WARNING] 12252 --- [Thread-17] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 17:44:03,606  [WARNING] 3936 --- [Thread-18] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 17:44:47,534  [WARNING] 3936 --- [Thread-18] [django.request:230][log:log_response]: Not Found: /teacher/findAll
2021-06-13 17:44:47,536  [WARNING] 12252 --- [Thread-17] [django.request:230][log:log_response]: Not Found: /subject/getAllSubject
2021-06-13 18:01:35,633  [ERROR] 3936 --- [Thread-2] [django.request:230][log:log_response]: Internal Server Error: /course
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\utils\deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\middleware\common.py", line 94, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.0.105:8000/course/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2021-06-13 18:03:24,699  [WARNING] 2388 --- [Thread-3] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-13 21:53:31,045  [INFO] 5700 --- [Thread-1] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-13 21:56:24,052  [WARNING] 5700 --- [Thread-1] [django.request:230][log:log_response]: Forbidden: /course/upload
2021-06-13 21:59:33,589  [WARNING] 4108 --- [Thread-1] [django.request:230][log:log_response]: Forbidden: /course/upload
2021-06-13 22:00:21,823  [WARNING] 17136 --- [Thread-1] [django.request:230][log:log_response]: Bad Request: /course/upload
2021-06-13 22:01:47,855  [WARNING] 16360 --- [Thread-1] [django.request:230][log:log_response]: Bad Request: /course/upload
2021-06-13 22:03:46,836  [WARNING] 16108 --- [Thread-2] [django.request:230][log:log_response]: Bad Request: /course/upload
2021-06-13 22:04:04,842  [WARNING] 16108 --- [Thread-2] [django.request:230][log:log_response]: Bad Request: /course/upload
2021-06-13 22:05:02,361  [WARNING] 16108 --- [Thread-2] [django.request:230][log:log_response]: Bad Request: /course/upload
2021-06-13 22:06:24,796  [WARNING] 13480 --- [Thread-1] [django.request:230][log:log_response]: Bad Request: /course/upload
2021-06-13 22:07:29,888  [WARNING] 13480 --- [Thread-1] [django.request:230][log:log_response]: Bad Request: /course/upload
2021-06-13 22:10:00,714  [INFO] 12708 --- [Thread-1] [course.views:121][views:post]: 上传file.jpg成功！
2021-06-13 22:11:49,155  [INFO] 12708 --- [Thread-1] [course.views:121][views:post]: 上传file.jpg成功！
2021-06-13 22:13:18,743  [INFO] 12708 --- [Thread-1] [course.views:121][views:post]: 上传file.jpg成功！
2021-06-13 22:14:04,929  [INFO] 12708 --- [Thread-1] [course.views:121][views:post]: 上传file.jpg成功！
2021-06-13 22:15:30,578  [INFO] 12464 --- [Thread-1] [course.views:122][views:post]: 上传file.jpg成功！
2021-06-13 22:26:39,298  [ERROR] 4720 --- [Thread-1] [django.request:230][log:log_response]: Internal Server Error: /course
Traceback (most recent call last):
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\utils\deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "C:\Users\TJ\PycharmProjects\SharePlatform\venv\lib\site-packages\django\middleware\common.py", line 94, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.0.105:8000/course/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2021-06-13 22:27:33,638  [WARNING] 17340 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /course
2021-06-13 22:32:23,705  [WARNING] 2056 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /course
2021-06-13 22:37:45,745  [INFO] 7364 --- [Thread-1] [course.views:125][views:post]: 上传file.jpg成功！
2021-06-13 22:37:47,733  [WARNING] 7364 --- [Thread-1] [django.request:230][log:log_response]: Unauthorized: /course
2021-06-13 22:44:01,031  [INFO] 16584 --- [Thread-4] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-13 22:44:17,933  [INFO] 16584 --- [Thread-4] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-13 22:44:55,893  [INFO] 16584 --- [Thread-4] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-13 22:45:00,821  [INFO] 16584 --- [Thread-4] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-13 22:45:08,764  [WARNING] 16584 --- [Thread-4] [django.request:230][log:log_response]: Not Found: /course/
2021-06-13 22:50:20,389  [INFO] 11468 --- [Thread-7] [course.views:125][views:post]: 上传cplus.jpg成功！
2021-06-13 22:50:24,808  [WARNING] 1944 --- [Thread-9] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-13 22:51:54,087  [WARNING] 11468 --- [Thread-7] [django.request:230][log:log_response]: Not Found: /course/
2021-06-13 22:56:47,487  [WARNING] 6692 --- [Thread-4] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-13 22:57:58,489  [WARNING] 6692 --- [Thread-4] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-13 22:58:50,481  [WARNING] 6692 --- [Thread-4] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-13 23:00:33,955  [WARNING] 9444 --- [Thread-10] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-13 23:02:12,731  [INFO] 11212 --- [Thread-12] [login.views:53][views:post]: 教师sa20225555登录成功！
2021-06-13 23:02:17,458  [WARNING] 6352 --- [Thread-14] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-13 23:03:34,204  [WARNING] 6352 --- [Thread-14] [django.request:230][log:log_response]: Not Found: /course/getMycourse
2021-06-13 23:03:56,596  [WARNING] 6352 --- [Thread-14] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
2021-06-13 23:04:23,017  [WARNING] 6352 --- [Thread-14] [django.request:230][log:log_response]: Not Found: /teacher/getTeacher/teacher-token
